version: '3.8'
services:
  devcontainer:
    build:
      context: ../
      dockerfile: .devcontainer/Dockerfile
    command: sleep infinity
    container_name: dev-rsl
    environment:
      - DISPLAY=${DISPLAY}
      - QT_X11_NO_MITSHM=1
      - ROS_DOMAIN_ID=99
    extra_hosts:
      - rsl:127.0.0.1
    hostname: rsl
    image: rsl:latest
    network_mode: host
    privileged: true
    user: dev
    volumes:
      - ../:/home/dev/rsl
      - ~/.ssh:/home/dev/.ssh:ro
      - ~/.gitconfig:/home/dev/.gitconfig:ro
      - ~/.local/.rsl/ccache:/home/dev/.ccache
      - ~/.local/.rsl/ros:/home/dev/.ros
      - /tmp/.X11-unix:/tmp/.X11-unix:ro
      - ${SSH_AUTH_SOCK}:${SSH_AUTH_SOCK}
    working_dir: /home/rsl
