name: Format

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main

jobs:
  pre-commit:
    name: pre-commit (${{ matrix.ubuntu-version }})
    runs-on: ubuntu-${{ matrix.ubuntu-version }}
    strategy:
      fail-fast: false
      matrix:
        ubuntu-version: [24.04, 26.04]
    steps:
      - uses: actions/checkout@v7
      - uses: actions/setup-python@v6
      - name: Install clang-format
        run: sudo apt-get install clang-format
      - uses: pre-commit/action@v3.0.1
