name: Tidy

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main

jobs:
  pre-commit:
    name: pre-commit
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
      - name: Install clang-tidy-14
        run: sudo apt-get install clang-tidy-14
      - uses: pre-commit/action@v3.0.0
